### ISSUE TITLE
it cant build

### ISSUE THREAD

**Issue by zodman** [Tecnativa/docker-odoo-base#96]
```
Step 1/1 : FROM tecnativa/odoo-base:10.0
10.0: Pulling from tecnativa/odoo-base
Digest: sha256:8d22ca6a503f9258a6ff1e12d05900636f20910124f8defc41a078e541ba6348
Status: Image is up to date for tecnativa/odoo-base:10.0
[91m# Executing 27 build triggers...
[0mStep 1/1 : ENTRYPOINT /opt/odoo/common/entrypoint
 ---> Using cache
Step 1/1 : CMD /usr/local/bin/odoo
 ---> Using cache
Step 1/1 : ARG AGGREGATE=true
 ---> Using cache
Step 1/1 : ARG AUTO_REQUIREMENTS=false
 ---> Using cache
Step 1/1 : ARG DEPTH_DEFAULT=1
 ---> Using cache
Step 1/1 : ARG DEPTH_MERGE=100
 ---> Using cache
Step 1/1 : ARG CLEAN=true
 ---> Using cache
Step 1/1 : ARG COMPILE=true
 ---> Using cache
Step 1/1 : ARG CONFIG_BUILD=true
 ---> Using cache
Step 1/1 : ARG PIP_INSTALL_ODOO=true
 ---> Using cache
Step 1/1 : ARG ADMIN_PASSWORD=admin
 ---> Using cache
Step 1/1 : ARG SMTP_SERVER=smtp
 ---> Using cache
Step 1/1 : ARG PROXY_MODE=false
 ---> Using cache
Step 1/1 : ARG WITHOUT_DEMO=all
 ---> Using cache
Step 1/1 : ARG PYTHONOPTIMIZE=1
 ---> Using cache
Step 1/1 : ENV PYTHONOPTIMIZE "$PYTHONOPTIMIZE"
 ---> Using cache
Step 1/1 : ARG PGUSER=odoo
 ---> Using cache
Step 1/1 : ARG PGPASSWORD=odoopassword
 ---> Using cache
Step 1/1 : ARG PGHOST=db
 ---> Using cache
Step 1/1 : ARG PGDATABASE=prod
 ---> Using cache
Step 1/1 : ENV ADMIN_PASSWORD "$ADMIN_PASSWORD" UNACCENT "$UNACCENT" PGUSER "$PGUSER" PGPASSWORD "$PGPASSWORD" PGHOST "$PGHOST" PGDATABASE "$PGDATABASE" PROXY_MODE "$PROXY_MODE" SMTP_SERVER "$SMTP_SERVER" WITHOUT_DEMO "$WITHOUT_DEMO"
 ---> Using cache
Step 1/1 : ARG LOCAL_CUSTOM_DIR=./custom
 ---> Using cache
Step 1/1 : COPY $LOCAL_CUSTOM_DIR /opt/odoo/custom
 ---> Using cache
Step 1/1 : ARG LOG_LEVEL=INFO
 ---> Using cache
Step 1/1 : RUN mkdir -p /opt/odoo/custom/ssh             && ln -s /opt/odoo/custom/ssh ~root/.ssh             && chmod -R u=rwX,go= /opt/odoo/custom/ssh             && sync
 ---> Using cache
Step 1/1 : RUN /opt/odoo/common/build && sync
 ---> Running in b876662326fa
[91mTraceback (most recent call last):
  File "/opt/odoo/common/build", line 28, in <module>
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
ERROR: Service 'odoo' failed to build: The command '/bin/sh -c /opt/odoo/common/build && sync' returned a non-zero code: 1
[0m
```

**Comment by Yajo** [comment]
Please add `--build-arg LOG_LEVEL=DEBUG`, build again and put the logs.

**Comment by zodman** [comment]
```
Step 1/1 : FROM tecnativa/odoo-base:10.0
[91m# Executing 27 build triggers...
[0mStep 1/1 : ENTRYPOINT /opt/odoo/common/entrypoint
 ---> Using cache
Step 1/1 : CMD /usr/local/bin/odoo
 ---> Using cache
Step 1/1 : ARG AGGREGATE=true
 ---> Using cache
Step 1/1 : ARG AUTO_REQUIREMENTS=false
 ---> Using cache
Step 1/1 : ARG DEPTH_DEFAULT=1
 ---> Using cache
Step 1/1 : ARG DEPTH_MERGE=100
 ---> Using cache
Step 1/1 : ARG CLEAN=true
 ---> Using cache
Step 1/1 : ARG COMPILE=true
 ---> Using cache
Step 1/1 : ARG CONFIG_BUILD=true
 ---> Using cache
Step 1/1 : ARG PIP_INSTALL_ODOO=true
 ---> Using cache
Step 1/1 : ARG ADMIN_PASSWORD=admin
 ---> Using cache
Step 1/1 : ARG SMTP_SERVER=smtp
 ---> Using cache
Step 1/1 : ARG PROXY_MODE=false
 ---> Using cache
Step 1/1 : ARG WITHOUT_DEMO=all
 ---> Using cache
Step 1/1 : ARG PYTHONOPTIMIZE=1
 ---> Using cache
Step 1/1 : ENV PYTHONOPTIMIZE "$PYTHONOPTIMIZE"
 ---> Using cache
Step 1/1 : ARG PGUSER=odoo
 ---> Using cache
Step 1/1 : ARG PGPASSWORD=odoopassword
 ---> Using cache
Step 1/1 : ARG PGHOST=db
 ---> Using cache
Step 1/1 : ARG PGDATABASE=prod
 ---> Using cache
Step 1/1 : ENV ADMIN_PASSWORD "$ADMIN_PASSWORD" UNACCENT "$UNACCENT" PGUSER "$PGUSER" PGPASSWORD "$PGPASSWORD" PGHOST "$PGHOST" PGDATABASE "$PGDATABASE" PROXY_MODE "$PROXY_MODE" SMTP_SERVER "$SMTP_SERVER" WITHOUT_DEMO "$WITHOUT_DEMO"
 ---> Using cache
Step 1/1 : ARG LOCAL_CUSTOM_DIR=./custom
 ---> Using cache
Step 1/1 : COPY $LOCAL_CUSTOM_DIR /opt/odoo/custom
 ---> Using cache
Step 1/1 : ARG LOG_LEVEL=INFO
 ---> Using cache
Step 1/1 : RUN mkdir -p /opt/odoo/custom/ssh             && ln -s /opt/odoo/custom/ssh ~root/.ssh             && chmod -R u=rwX,go= /opt/odoo/custom/ssh             && sync
 ---> Using cache
Step 1/1 : RUN /opt/odoo/common/build && sync
 ---> Running in 9151034b5650
[91mDEBUG:docker-odoo-base:Executing /opt/odoo/custom/build.d/.empty
[0m[91mTraceback (most recent call last):
  File "/opt/odoo/common/build", line 28, in <module>
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
[0m
```

**Comment by Yajo** [comment]
```
�[91mDEBUG:docker-odoo-base:Executing /opt/odoo/custom/build.d/.empty
```

☝️ There's the problem. Either remove the file or set it as non-executable. 😊

**Comment by zodman** [comment]
its from docker container base from tecnativa ... i cant remove or change de +x perm

**Comment by Yajo** [comment]
It doesn't have a x perm in our repo, you probably have a local problem with your `umask` or something like that. In any case you can always change permissions on files you own, just use `chmod` for that 😉
